/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import clases.*;

/**
 *
 * @author Narcis
 */
public class VentanaJugarIndividual extends javax.swing.JFrame {

    private JFrame principal;
    private ArrayList<Carta> mano;
    private static Jugador_registrado jug;
    private ListIterator li;
    private Carta carta;
    private final HashMap<String, Jugador_registrado> jugadores;

    /**
     * Creates new form VentanaJugar
     *
     * @param ventana
     */
    public VentanaJugarIndividual(JFrame ventana) {
        initComponents();
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        jugadores = CasaApuestas.getJug();
        jug = jugadores.get(VentanaJugadorRegistrado.jTextFieldNIF.getText());
        jTextFieldSaldoAcumulado.setText(String.valueOf(jug.getSaldo_acumulado()) + "€");
    }

    public static Jugador_registrado getJugPlaying() {
        return jug;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonApostar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxCantidad = new javax.swing.JComboBox<>();
        jButtonVolver = new javax.swing.JButton();
        jTextFieldSaldoAcumulado = new javax.swing.JTextField();
        jButtonAumentarSaldo = new javax.swing.JButton();
        jTextFieldCantAumSald = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonRetBenef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonApostar.setText("APOSTAR");
        jButtonApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApostarActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("Cantidad que desea apostar");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBoxCantidad.setEditable(true);
        jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "60", "70", "80", "90", "100", "125", "150", "175", "200", "250", "300", "350", "400", "450", "500", "600", "700", "800", "900", "1000" }));
        jComboBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCantidadActionPerformed(evt);
            }
        });

        jButtonVolver.setText("VOLVER");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jTextFieldSaldoAcumulado.setEditable(false);

        jButtonAumentarSaldo.setText("AUMENTAR SALDO");
        jButtonAumentarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentarSaldoActionPerformed(evt);
            }
        });

        jTextFieldCantAumSald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantAumSaldActionPerformed(evt);
            }
        });

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonRetBenef.setText("RETIRAR BENEFICIOS");
        jButtonRetBenef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetBenefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAumentarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 324, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSaldoAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonRetBenef, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jButtonApostar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 32, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCantAumSald, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButtonApostar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAumentarSaldo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRetBenef)
                            .addComponent(jTextFieldSaldoAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVolver))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCantAumSald, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButtonApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApostarActionPerformed
        if (Double.parseDouble((String) jComboBoxCantidad.getSelectedItem()) > jug.getSaldo_acumulado()) {
            JOptionPane.showMessageDialog(this, "Saldo Insuficiente", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            Baraja baraja = new Baraja();
            mano = baraja.crearMano();
            Apuesta apuesta = new Apuesta(Double.parseDouble((String) jComboBoxCantidad.getSelectedItem()), mano);
            
            apuesta.verPremio(mano);
            jug.setSaldo_acumulado(jug.getSaldo_acumulado() - Double.parseDouble((String) jComboBoxCantidad.getSelectedItem()));
            if (!apuesta.verPremioEstad(mano).equals("Nada")) {
                Premio premio = new Premio(apuesta.verPremioEstad(mano), jug.getSaldo_acumulado()
                        - Double.parseDouble((String) jTextFieldSaldoAcumulado.getText()),
                        "Individual", jug);
            }
            jTextFieldSaldoAcumulado.setText(String.valueOf(jug.getSaldo_acumulado()));
            Carta.ordenarCartas(mano);

            jButton1.setIcon(new ImageIcon("C:\\Users\\Narcis\\Desktop\\Poker\\" + mano.get(0).getPalo() + "\\" + mano.get(0).getCara() + ".jpg"));
            jButton2.setIcon(new ImageIcon("C:\\Users\\Narcis\\Desktop\\Poker\\" + mano.get(1).getPalo() + "\\" + mano.get(1).getCara() + ".jpg"));
            jButton3.setIcon(new ImageIcon("C:\\Users\\Narcis\\Desktop\\Poker\\" + mano.get(2).getPalo() + "\\" + mano.get(2).getCara() + ".jpg"));
            jButton4.setIcon(new ImageIcon("C:\\Users\\Narcis\\Desktop\\Poker\\" + mano.get(3).getPalo() + "\\" + mano.get(3).getCara() + ".jpg"));
            jButton5.setIcon(new ImageIcon("C:\\Users\\Narcis\\Desktop\\Poker\\" + mano.get(4).getPalo() + "\\" + mano.get(4).getCara() + ".jpg"));

        }


    }//GEN-LAST:event_jButtonApostarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonAumentarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentarSaldoActionPerformed
        double aum_saldo;
        aum_saldo = Double.parseDouble(jTextFieldCantAumSald.getText());
        jug.setSaldo_acumulado(jug.getSaldo_acumulado() + aum_saldo);
        JOptionPane.showMessageDialog(this, "Has aumentado tu saldo en:" + aum_saldo, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        jTextFieldCantAumSald.setText(null);
        jTextFieldSaldoAcumulado.setText(String.valueOf(jug.getSaldo_acumulado()) + "€");

    }//GEN-LAST:event_jButtonAumentarSaldoActionPerformed

    private void jComboBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCantidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldCantAumSaldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantAumSaldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantAumSaldActionPerformed

    private void jButtonRetBenefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetBenefActionPerformed
        JOptionPane.showMessageDialog(this, "Has retirado tu dinero.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        try {
            CasaApuestas.generaFactura(jug);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error.", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        jug.retirarBeneficios();
        jTextFieldSaldoAcumulado.setText(String.valueOf(0));


    }//GEN-LAST:event_jButtonRetBenefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        CasaApuestas.guardarDatos();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonApostar;
    private javax.swing.JButton jButtonAumentarSaldo;
    private javax.swing.JButton jButtonRetBenef;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxCantidad;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCantAumSald;
    private javax.swing.JTextField jTextFieldSaldoAcumulado;
    // End of variables declaration//GEN-END:variables
}
